numShippers: 2
numTransformers: 2
reader:
  joinContainerPartial: 180000
  cursorFile: "journal.cursor"
  fieldNames:
   - MESSAGE
   - PRIORITY
formatters:
  - type: lowercase
  - type: unmarshal
    inputPath: 'message'
  - type: add
    fields:
      service_id: 'rxz1k'
  - type: jsone
    template: {$eval: fields}
shipper:
  type: kinesis
  region: 'us-west-1'
  streamName: 'arn:aws:kinesis:us-west-1111122223333:stream/my-stream'
