// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kpl-aggregation.proto

package shippers

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AggregatedRecord struct {
	PartitionKeyTable    []string  `protobuf:"bytes,1,rep,name=partition_key_table,json=partitionKeyTable" json:"partition_key_table,omitempty"`
	ExplicitHashKeyTable []string  `protobuf:"bytes,2,rep,name=explicit_hash_key_table,json=explicitHashKeyTable" json:"explicit_hash_key_table,omitempty"`
	Records              []*Record `protobuf:"bytes,3,rep,name=records" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AggregatedRecord) Reset()         { *m = AggregatedRecord{} }
func (m *AggregatedRecord) String() string { return proto.CompactTextString(m) }
func (*AggregatedRecord) ProtoMessage()    {}
func (*AggregatedRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c98aee8989e914e, []int{0}
}

func (m *AggregatedRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatedRecord.Unmarshal(m, b)
}
func (m *AggregatedRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatedRecord.Marshal(b, m, deterministic)
}
func (m *AggregatedRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatedRecord.Merge(m, src)
}
func (m *AggregatedRecord) XXX_Size() int {
	return xxx_messageInfo_AggregatedRecord.Size(m)
}
func (m *AggregatedRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatedRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatedRecord proto.InternalMessageInfo

func (m *AggregatedRecord) GetPartitionKeyTable() []string {
	if m != nil {
		return m.PartitionKeyTable
	}
	return nil
}

func (m *AggregatedRecord) GetExplicitHashKeyTable() []string {
	if m != nil {
		return m.ExplicitHashKeyTable
	}
	return nil
}

func (m *AggregatedRecord) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type Tag struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c98aee8989e914e, []int{1}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Tag) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Record struct {
	PartitionKeyIndex    *uint64  `protobuf:"varint,1,req,name=partition_key_index,json=partitionKeyIndex" json:"partition_key_index,omitempty"`
	ExplicitHashKeyIndex *uint64  `protobuf:"varint,2,opt,name=explicit_hash_key_index,json=explicitHashKeyIndex" json:"explicit_hash_key_index,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c98aee8989e914e, []int{2}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetPartitionKeyIndex() uint64 {
	if m != nil && m.PartitionKeyIndex != nil {
		return *m.PartitionKeyIndex
	}
	return 0
}

func (m *Record) GetExplicitHashKeyIndex() uint64 {
	if m != nil && m.ExplicitHashKeyIndex != nil {
		return *m.ExplicitHashKeyIndex
	}
	return 0
}

func (m *Record) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Record) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*AggregatedRecord)(nil), "AggregatedRecord")
	proto.RegisterType((*Tag)(nil), "Tag")
	proto.RegisterType((*Record)(nil), "Record")
}

func init() { proto.RegisterFile("kpl-aggregation.proto", fileDescriptor_2c98aee8989e914e) }

var fileDescriptor_2c98aee8989e914e = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xc1, 0x4e, 0xc4, 0x20,
	0x10, 0x86, 0x43, 0x41, 0x37, 0x1d, 0x3d, 0xac, 0xb8, 0x46, 0x8e, 0xb5, 0x27, 0x2e, 0xdb, 0x83,
	0x89, 0x0f, 0xe0, 0x4d, 0xe3, 0x8d, 0xf4, 0xde, 0x8c, 0x2d, 0xa1, 0xa4, 0xcd, 0xb6, 0xa1, 0x68,
	0xb6, 0xef, 0xa2, 0xef, 0x6a, 0xa0, 0xee, 0x46, 0xa3, 0x7b, 0x1b, 0xe6, 0xe7, 0xe3, 0xe7, 0x83,
	0x9b, 0xae, 0xee, 0xb7, 0x68, 0x8c, 0xd3, 0x06, 0xbd, 0x1d, 0x76, 0xc5, 0xe8, 0x06, 0x3f, 0xe4,
	0x1f, 0x04, 0xd6, 0x8f, 0xdf, 0x5b, 0xdd, 0x28, 0x5d, 0x0f, 0xae, 0xe1, 0x05, 0x5c, 0x8f, 0xe8,
	0xbc, 0x0d, 0xf7, 0xaa, 0x4e, 0xcf, 0x95, 0xc7, 0xd7, 0x5e, 0x0b, 0x92, 0x51, 0x99, 0xaa, 0xab,
	0x63, 0xf4, 0xa2, 0xe7, 0x32, 0x04, 0xfc, 0x01, 0x6e, 0xf5, 0x7e, 0xec, 0x6d, 0x6d, 0x7d, 0xd5,
	0xe2, 0xd4, 0xfe, 0x60, 0x92, 0xc8, 0x6c, 0x0e, 0xf1, 0x13, 0x4e, 0xed, 0x11, 0xbb, 0x83, 0x95,
	0x8b, 0x85, 0x93, 0xa0, 0x19, 0x95, 0x17, 0xf7, 0xab, 0x62, 0xf9, 0x80, 0x3a, 0xec, 0xf3, 0x2d,
	0xd0, 0x12, 0x0d, 0x5f, 0x03, 0xed, 0xf4, 0x2c, 0x48, 0x96, 0xc8, 0x54, 0x85, 0x91, 0x6f, 0xe0,
	0xec, 0x1d, 0xfb, 0xb7, 0x50, 0x40, 0x64, 0xaa, 0x96, 0x43, 0xfe, 0x49, 0xe0, 0xfc, 0x94, 0x83,
	0xdd, 0x35, 0x7a, 0x1f, 0x9f, 0x60, 0xbf, 0x1d, 0x9e, 0x43, 0xf0, 0xbf, 0xc3, 0xc2, 0x84, 0x0a,
	0xf6, 0xc7, 0x61, 0xc1, 0x38, 0xb0, 0x06, 0x3d, 0x0a, 0x9a, 0x25, 0xf2, 0x52, 0xc5, 0x99, 0x0b,
	0x60, 0x1e, 0xcd, 0x24, 0x58, 0x94, 0x62, 0x45, 0x89, 0x46, 0xc5, 0xcd, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x82, 0x9f, 0xf7, 0xe9, 0x85, 0x01, 0x00, 0x00,
}
